# Generated by Django 3.1.3 on 2020-11-26 03:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=25, unique=True, verbose_name='English')),
                ('img', models.ImageField(upload_to='static/img')),
                ('themeLink', models.CharField(default='https://youtu.be/75p-N9YKqNo', max_length=50, verbose_name='Link')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engWord', models.CharField(max_length=25, verbose_name='English')),
                ('trWord', models.CharField(max_length=25, verbose_name='Ukrainian')),
                ('sentence', models.TextField(verbose_name='Sentence')),
                ('structure', models.CharField(max_length=25, verbose_name='Structure')),
                ('img', models.ImageField(upload_to='static/img/words')),
                ('brainteaser', models.TextField(default=None, verbose_name='Brainteaser')),
                ('word', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='word.theme', verbose_name='Theme')),
            ],
        ),
        migrations.CreateModel(
            name='WordKnowledge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Date to ask')),
                ('level', models.IntegerField(verbose_name='Level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word', verbose_name='Word')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='Memorization Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='word.word', verbose_name='Word')),
            ],
        ),
    ]
